-- =============================================================================
-- 02_terminology.sql
-- Reference vocabularies & crosswalks.
--
-- Lightweight for the POC: the silver tables carry inline (*_code / *_system /
-- *_display) so analytics are NOT blocked on a full vocabulary load. Populate
-- these incrementally; silver *_concept_sk columns can link here once loaded.
--
-- NOTE: PRIMARY KEY / FOREIGN KEY are INFORMATIONAL ONLY in Databricks
-- (not enforced at write time). They document intent and aid the optimizer.
-- The ETL layer is responsible for referential integrity.
-- =============================================================================

CREATE TABLE IF NOT EXISTS ehr_poc.terminology.code_system (
  code_system     STRING  NOT NULL COMMENT 'e.g. ICD-10-CM, RxNorm, LOINC, CPT, HCPCS, SNOMED',
  system_uri      STRING  COMMENT 'Canonical FHIR/HL7 system URI',
  version         STRING,
  description     STRING,
  loaded_at       TIMESTAMP DEFAULT current_timestamp(),
  CONSTRAINT pk_code_system PRIMARY KEY (code_system)
)
COMMENT 'Registry of standard code systems used across the model.';

CREATE TABLE IF NOT EXISTS ehr_poc.terminology.concept (
  concept_sk      BIGINT GENERATED BY DEFAULT AS IDENTITY,
  code_system     STRING NOT NULL COMMENT 'FK -> code_system.code_system',
  code            STRING NOT NULL,
  display         STRING,
  concept_class   STRING COMMENT 'e.g. diagnosis, ingredient, lab-test, procedure',
  maps_to_snomed  STRING COMMENT 'Optional crosswalk to a standard SNOMED concept',
  is_standard     BOOLEAN DEFAULT false,
  loaded_at       TIMESTAMP DEFAULT current_timestamp(),
  CONSTRAINT pk_concept PRIMARY KEY (concept_sk),
  CONSTRAINT fk_concept_system FOREIGN KEY (code_system) REFERENCES ehr_poc.terminology.code_system
)
COMMENT 'Concepts within each code system, with optional SNOMED crosswalk.';
