

-- =============================================================================
-- 03_poc_clinical_tables.sql
-- Core clinical domain tables for the Synthetic EHR POC.
-- All tables live in ehr_poc.clinical (single schema, no medallion layers).
--
-- Tables: patient, encounter, condition, observation,
--         medication_order, procedure, clinical_note
--
-- Conventions:
--   * Surrogate PK *_sk: BIGINT GENERATED BY DEFAULT AS IDENTITY
--   * Code trio: *_code / *_system / *_display (no separate vocab tables)
--   * Constraints: INFORMATIONAL ONLY (NOT ENFORCED RELY) — not enforced at
--     write time; they document intent and help the Databricks optimizer
--   * Clustering: liquid CLUSTER BY instead of partitioning
--
-- Populate with Synthea-generated FHIR R4 or hand-authored synthetic data.
-- VARIANT requires DBR 15.3+; replace with STRING (JSON) on older runtimes.
-- Run after 01_catalog_and_schemas.sql.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- patient
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dev.test_silver_ehr_clinical.patient (
  patient_sk        BIGINT GENERATED BY DEFAULT AS IDENTITY,
  mrn               STRING    NOT NULL  COMMENT 'Medical record number (synthetic)',
  birth_date        DATE,
  sex               STRING              COMMENT 'administrative sex: male | female | other | unknown',
  gender_identity   STRING,
  race              STRING,
  ethnicity         STRING,
  deceased_flag     BOOLEAN   DEFAULT false,
  deceased_date     DATE,
  city              STRING,
  state             STRING,
  zip               STRING,
  primary_language  STRING    DEFAULT 'English',
  marital_status    STRING,
  loaded_at         TIMESTAMP DEFAULT current_timestamp(),
  CONSTRAINT pk_patient     PRIMARY KEY (patient_sk) NOT ENFORCED RELY
)
COMMENT 'Patient demographics. One row per patient. Populated with synthetic data.'
CLUSTER BY (patient_sk)
TBLPROPERTIES ('delta.feature.allowColumnDefaults' = 'supported');

-- ---------------------------------------------------------------------------
-- encounter
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dev.test_silver_ehr_clinical.encounter (
  encounter_sk             BIGINT GENERATED BY DEFAULT AS IDENTITY,
  patient_sk               BIGINT    NOT NULL,
  encounter_class          STRING              COMMENT 'inpatient | outpatient | emergency | ambulatory | telehealth',
  encounter_type           STRING              COMMENT 'human-readable visit type (e.g. Office Visit, ED Visit)',
  status                   STRING              COMMENT 'planned | arrived | in-progress | finished | cancelled',
  period_start             TIMESTAMP,
  period_end               TIMESTAMP,
  admit_source             STRING,
  discharge_disposition    STRING,
  attending_provider_name  STRING,
  facility_name            STRING,
  loaded_at                TIMESTAMP DEFAULT current_timestamp(),
  CONSTRAINT pk_encounter   PRIMARY KEY (encounter_sk) NOT ENFORCED RELY,
  CONSTRAINT fk_enc_patient FOREIGN KEY (patient_sk)   REFERENCES dev.test_silver_ehr_clinical.patient NOT ENFORCED RELY
)
COMMENT 'Patient encounters / visits. Provider and facility are stored as names (no reference tables needed for POC).'
CLUSTER BY (patient_sk, period_start)
TBLPROPERTIES ('delta.feature.allowColumnDefaults' = 'supported');

-- ---------------------------------------------------------------------------
-- condition  (diagnoses + problem list)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dev.test_silver_ehr_clinical.condition (
  condition_sk         BIGINT GENERATED BY DEFAULT AS IDENTITY,
  patient_sk           BIGINT    NOT NULL,
  encounter_sk         BIGINT              COMMENT 'NULL for problem-list items not tied to a specific visit',
  category             STRING              COMMENT 'problem-list-item | encounter-diagnosis',
  condition_code       STRING              COMMENT 'ICD-10-CM code (e.g. E11.9)',
  condition_system     STRING    DEFAULT 'ICD-10-CM',
  condition_display    STRING              COMMENT 'human-readable diagnosis name',
  clinical_status      STRING              COMMENT 'active | resolved | inactive',
  verification_status  STRING              COMMENT 'confirmed | provisional',
  rank                 INT                 COMMENT '1 = primary diagnosis',
  is_chronic           BOOLEAN   DEFAULT false,
  onset_date           DATE,
  recorded_date        DATE,
  resolved_date        DATE,
  loaded_at            TIMESTAMP DEFAULT current_timestamp(),
  CONSTRAINT pk_condition    PRIMARY KEY (condition_sk) NOT ENFORCED RELY,
  CONSTRAINT fk_cond_patient FOREIGN KEY (patient_sk)  REFERENCES dev.test_silver_ehr_clinical.patient NOT ENFORCED RELY
)
COMMENT 'Diagnoses and problem list items. ICD-10-CM coded.'
CLUSTER BY (patient_sk, recorded_date)
TBLPROPERTIES ('delta.feature.allowColumnDefaults' = 'supported');

-- ---------------------------------------------------------------------------
-- observation  (lab results AND vital signs — category discriminates)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dev.test_silver_ehr_clinical.observation (
  observation_sk        BIGINT GENERATED BY DEFAULT AS IDENTITY,
  patient_sk            BIGINT    NOT NULL,
  encounter_sk          BIGINT,
  category              STRING    NOT NULL  COMMENT 'laboratory | vital-signs',
  observation_code      STRING              COMMENT 'LOINC code (e.g. 4548-4 = HbA1c, 85354-9 = BP panel)',
  observation_system    STRING    DEFAULT 'LOINC',
  observation_display   STRING              COMMENT 'human-readable test or vital name',
  value_numeric         DOUBLE,
  value_string          STRING              COMMENT 'non-numeric or coded results (e.g. Positive, Negative)',
  unit                  STRING              COMMENT 'UCUM unit (e.g. mg/dL, mmHg, %)',
  reference_range_low   DOUBLE,
  reference_range_high  DOUBLE,
  interpretation        STRING              COMMENT 'normal | high | low | critical | abnormal',
  effective_datetime    TIMESTAMP,
  parent_observation_sk BIGINT              COMMENT 'for multi-component results — e.g. systolic/diastolic rows point to the BP panel row',
  loaded_at             TIMESTAMP DEFAULT current_timestamp(),
  CONSTRAINT pk_observation    PRIMARY KEY (observation_sk) NOT ENFORCED RELY,
  CONSTRAINT fk_obs_patient    FOREIGN KEY (patient_sk)     REFERENCES dev.test_silver_ehr_clinical.patient NOT ENFORCED RELY
)
COMMENT 'Lab results (category=laboratory) and vital signs (category=vital-signs) in one table. Filter by category.'
CLUSTER BY (patient_sk, effective_datetime)
TBLPROPERTIES ('delta.feature.allowColumnDefaults' = 'supported');

-- ---------------------------------------------------------------------------
-- medication_order  (prescriptions / inpatient orders)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dev.test_silver_ehr_clinical.medication_order (
  med_order_sk    BIGINT GENERATED BY DEFAULT AS IDENTITY,
  patient_sk      BIGINT    NOT NULL,
  encounter_sk    BIGINT,
  med_code        STRING              COMMENT 'RxNorm concept code (e.g. 860975 = metformin 500 mg oral tablet)',
  med_system      STRING    DEFAULT 'RxNorm',
  med_display     STRING              COMMENT 'medication name (generic preferred)',
  ndc_code        STRING              COMMENT 'NDC product code (optional)',
  order_class     STRING              COMMENT 'inpatient | outpatient',
  dose_quantity   STRING,
  dose_unit       STRING,
  route           STRING              COMMENT 'oral | IV | topical | subcutaneous | etc.',
  frequency       STRING              COMMENT 'daily | BID | TID | PRN | etc.',
  sig_text        STRING              COMMENT 'free-text dosing instructions',
  order_status    STRING              COMMENT 'active | completed | discontinued',
  start_datetime  TIMESTAMP,
  end_datetime    TIMESTAMP,
  loaded_at       TIMESTAMP DEFAULT current_timestamp(),
  CONSTRAINT pk_medication_order    PRIMARY KEY (med_order_sk) NOT ENFORCED RELY,
  CONSTRAINT fk_medord_patient      FOREIGN KEY (patient_sk)   REFERENCES dev.test_silver_ehr_clinical.patient NOT ENFORCED RELY
)
COMMENT 'Medication orders and prescriptions. RxNorm coded.'
CLUSTER BY (patient_sk, start_datetime)
TBLPROPERTIES ('delta.feature.allowColumnDefaults' = 'supported');

-- ---------------------------------------------------------------------------
-- procedure
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dev.test_silver_ehr_clinical.procedure (
  procedure_sk        BIGINT GENERATED BY DEFAULT AS IDENTITY,
  patient_sk          BIGINT    NOT NULL,
  encounter_sk        BIGINT,
  procedure_code      STRING              COMMENT 'CPT / HCPCS code (e.g. 93000 = ECG)',
  procedure_system    STRING    DEFAULT 'CPT',
  procedure_display   STRING              COMMENT 'human-readable procedure name',
  procedure_category  STRING              COMMENT 'surgical | diagnostic | therapeutic',
  status              STRING              COMMENT 'completed | in-progress',
  performed_datetime  TIMESTAMP,
  loaded_at           TIMESTAMP DEFAULT current_timestamp(),
  CONSTRAINT pk_procedure    PRIMARY KEY (procedure_sk) NOT ENFORCED RELY,
  CONSTRAINT fk_proc_patient FOREIGN KEY (patient_sk)   REFERENCES dev.test_silver_ehr_clinical.patient NOT ENFORCED RELY
)
COMMENT 'Clinical procedures. CPT / HCPCS coded.'
CLUSTER BY (patient_sk, performed_datetime)
TBLPROPERTIES ('delta.feature.allowColumnDefaults' = 'supported');

-- ---------------------------------------------------------------------------
-- clinical_note  (NLP centerpiece — full free text)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dev.test_silver_ehr_clinical.clinical_note (
  note_sk           BIGINT GENERATED BY DEFAULT AS IDENTITY,
  patient_sk        BIGINT    NOT NULL,
  encounter_sk      BIGINT,
  note_type_code    STRING              COMMENT 'LOINC document type code (e.g. 18842-5 = Discharge summary)',
  note_type_system  STRING    DEFAULT 'LOINC',
  note_type_display STRING              COMMENT 'Discharge Summary | Progress Note | H&P | Consult | Pathology Report | Radiology Report | etc.',
  note_category     STRING              COMMENT 'discharge_summary | progress | hp | consult | pathology | radiology | other',
  author_name       STRING,
  service_date      TIMESTAMP,
  status            STRING    DEFAULT 'signed'  COMMENT 'preliminary | signed | addended',
  note_text         STRING              COMMENT 'full plain-text note body — the primary NLP input. Include deliberate negation and temporality examples for demo.',
  loaded_at         TIMESTAMP DEFAULT current_timestamp(),
  CONSTRAINT pk_clinical_note    PRIMARY KEY (note_sk)    NOT ENFORCED RELY,
  CONSTRAINT fk_note_patient     FOREIGN KEY (patient_sk) REFERENCES dev.test_silver_ehr_clinical.patient NOT ENFORCED RELY
)
COMMENT 'Clinical notes with full free text. Discharge summaries, progress notes, path/rad reports. Source for NLP entity extraction.'
CLUSTER BY (patient_sk, service_date)
TBLPROPERTIES ('delta.feature.allowColumnDefaults' = 'supported');
