-- =============================================================================
-- 03_silver_clinical_model.sql
-- Conformed, FHIR-aligned, source-agnostic clinical model (the POC core).
--
-- Conventions:
--   * Surrogate PK *_sk : BIGINT GENERATED BY DEFAULT AS IDENTITY
--   * Business key      : (source_system, source_id) on every table
--   * Coding trio       : *_code / *_system / *_display (+ optional *_concept_sk)
--   * Provenance        : source_system, source_id, source_table_or_resource,
--                         ingested_at, loaded_at, raw_payload (VARIANT)
--   * Constraints       : INFORMATIONAL ONLY (not enforced) — ETL owns integrity
--   * Clustering        : liquid clustering (CLUSTER BY) instead of partitioning
--
-- VARIANT requires DBR 15.3+. On older runtimes replace VARIANT with STRING (JSON).
-- Tables are created in FK-dependency order.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Supporting / reference dimensions
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS ehr_poc.silver.organization (
  organization_sk           BIGINT GENERATED BY DEFAULT AS IDENTITY,
  source_system             STRING NOT NULL COMMENT 'epic | athena | synthea',
  source_id                 STRING NOT NULL COMMENT 'Epic SER/loc id | athena practiceid | FHIR Organization id',
  name                      STRING,
  org_type                  STRING COMMENT 'hospital | clinic | practice | lab',
  source_table_or_resource  STRING,
  ingested_at               TIMESTAMP,
  loaded_at                 TIMESTAMP DEFAULT current_timestamp(),
  raw_payload               VARIANT,
  CONSTRAINT pk_organization PRIMARY KEY (organization_sk)
)
COMMENT 'FHIR Organization — facility / practice.';

CREATE TABLE IF NOT EXISTS ehr_poc.silver.location (
  location_sk               BIGINT GENERATED BY DEFAULT AS IDENTITY,
  source_system             STRING NOT NULL,
  source_id                 STRING NOT NULL COMMENT 'Epic DEPARTMENT_ID/ROOM_ID | FHIR Location id',
  organization_sk           BIGINT,
  name                      STRING,
  location_type             STRING COMMENT 'department | unit | room | bed',
  source_table_or_resource  STRING,
  ingested_at               TIMESTAMP,
  loaded_at                 TIMESTAMP DEFAULT current_timestamp(),
  raw_payload               VARIANT,
  CONSTRAINT pk_location PRIMARY KEY (location_sk),
  CONSTRAINT fk_location_org FOREIGN KEY (organization_sk) REFERENCES ehr_poc.silver.organization
)
COMMENT 'FHIR Location — department / unit / room.';

CREATE TABLE IF NOT EXISTS ehr_poc.silver.provider (
  provider_sk               BIGINT GENERATED BY DEFAULT AS IDENTITY,
  source_system             STRING NOT NULL,
  source_id                 STRING NOT NULL COMMENT 'Epic PROV_ID/SER | athena providerid | FHIR Practitioner id',
  npi                       STRING,
  full_name                 STRING,
  specialty                 STRING,
  source_table_or_resource  STRING,
  ingested_at               TIMESTAMP,
  loaded_at                 TIMESTAMP DEFAULT current_timestamp(),
  raw_payload               VARIANT,
  CONSTRAINT pk_provider PRIMARY KEY (provider_sk)
)
COMMENT 'FHIR Practitioner — clinicians/authors.';

-- -----------------------------------------------------------------------------
-- Domain 1 — Patient Demographics
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS ehr_poc.silver.patient (
  patient_sk                BIGINT GENERATED BY DEFAULT AS IDENTITY,
  source_system             STRING NOT NULL,
  source_id                 STRING NOT NULL COMMENT 'Epic PAT_ID | athena patientid | FHIR Patient id',
  mrn                       STRING COMMENT 'Primary MRN (full set in patient_identifier)',
  birth_date                DATE,
  sex                       STRING COMMENT 'administrative: male | female | other | unknown',
  gender_identity           STRING,
  race                      STRING,
  ethnicity                 STRING,
  deceased_flag             BOOLEAN DEFAULT false,
  deceased_date             DATE,
  address_line_1            STRING,
  address_line_2            STRING,
  city                      STRING,
  state                     STRING,
  zip                       STRING,
  primary_language          STRING,
  marital_status            STRING,
  source_table_or_resource  STRING,
  ingested_at               TIMESTAMP,
  loaded_at                 TIMESTAMP DEFAULT current_timestamp(),
  raw_payload               VARIANT,
  CONSTRAINT pk_patient PRIMARY KEY (patient_sk)
)
COMMENT 'Conformed patient master. Epic: PATIENT/PATIENT_2..4/PATIENT_RACE/IDENTITY_ID. athena: Patient FHIR.'
CLUSTER BY (source_system, source_id);

CREATE TABLE IF NOT EXISTS ehr_poc.silver.patient_identifier (
  patient_identifier_sk     BIGINT GENERATED BY DEFAULT AS IDENTITY,
  patient_sk                BIGINT NOT NULL,
  identifier_type           STRING NOT NULL COMMENT 'mrn | enterprise_id | source_pat_id | member_id | ssn_last4',
  identifier_value          STRING NOT NULL,
  assigning_authority       STRING COMMENT 'Issuing system/facility (e.g. Epic facility, athena practiceid)',
  source_system             STRING NOT NULL,
  loaded_at                 TIMESTAMP DEFAULT current_timestamp(),
  CONSTRAINT pk_patient_identifier PRIMARY KEY (patient_identifier_sk),
  CONSTRAINT fk_patid_patient FOREIGN KEY (patient_sk) REFERENCES ehr_poc.silver.patient
)
COMMENT 'All identifiers per patient — the cross-source identity-resolution table.'
CLUSTER BY (patient_sk);

-- -----------------------------------------------------------------------------
-- Domain 2 — Encounters / Visits
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS ehr_poc.silver.encounter (
  encounter_sk              BIGINT GENERATED BY DEFAULT AS IDENTITY,
  patient_sk                BIGINT NOT NULL,
  source_system             STRING NOT NULL,
  source_id                 STRING NOT NULL COMMENT 'Epic PAT_ENC_CSN_ID | FHIR Encounter id',
  encounter_class           STRING COMMENT 'inpatient | outpatient | emergency | ambulatory | telehealth',
  encounter_type_code       STRING,
  encounter_type_system     STRING,
  encounter_type_display    STRING,
  status                    STRING COMMENT 'planned | arrived | in-progress | finished | cancelled',
  period_start              TIMESTAMP,
  period_end                TIMESTAMP,
  admit_source              STRING,
  discharge_disposition     STRING,
  attending_provider_sk     BIGINT,
  organization_sk           BIGINT,
  location_sk               BIGINT,
  hospital_account_id       STRING COMMENT 'Epic HAR (HSP_ACCOUNT_ID) linkage',
  source_table_or_resource  STRING,
  ingested_at               TIMESTAMP,
  loaded_at                 TIMESTAMP DEFAULT current_timestamp(),
  raw_payload               VARIANT,
  CONSTRAINT pk_encounter PRIMARY KEY (encounter_sk),
  CONSTRAINT fk_enc_patient  FOREIGN KEY (patient_sk)            REFERENCES ehr_poc.silver.patient,
  CONSTRAINT fk_enc_provider FOREIGN KEY (attending_provider_sk) REFERENCES ehr_poc.silver.provider,
  CONSTRAINT fk_enc_org      FOREIGN KEY (organization_sk)       REFERENCES ehr_poc.silver.organization,
  CONSTRAINT fk_enc_location FOREIGN KEY (location_sk)           REFERENCES ehr_poc.silver.location
)
COMMENT 'Encounters/visits. Epic: PAT_ENC/PAT_ENC_HSP/CLARITY_ADT/HSP_ACCOUNT. athena: Encounter (Appointment != Encounter).'
CLUSTER BY (patient_sk, period_start);

-- -----------------------------------------------------------------------------
-- Domain 3 — Clinical Notes  (NLP centerpiece)
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS ehr_poc.silver.clinical_note (
  note_sk                   BIGINT GENERATED BY DEFAULT AS IDENTITY,
  patient_sk                BIGINT NOT NULL,
  encounter_sk              BIGINT,
  source_system             STRING NOT NULL,
  source_id                 STRING NOT NULL COMMENT 'Epic NOTE_ID(+NOTE_CSN_ID) | athena DocumentReference id',
  note_type_code            STRING COMMENT 'LOINC document type code',
  note_type_system          STRING,
  note_type_display         STRING,
  note_category             STRING COMMENT 'discharge_summary | progress | hp | consult | pathology | radiology | other',
  author_provider_sk        BIGINT,
  service_date              TIMESTAMP,
  created_at                TIMESTAMP,
  signed_at                 TIMESTAMP,
  status                    STRING COMMENT 'preliminary | signed | addended',
  note_text                 STRING COMMENT 'FULL reassembled plain text — the NLP input',
  content_type              STRING COMMENT 'original: text/plain | text/html | application/pdf | image/tiff',
  text_extraction_method    STRING COMMENT 'structured_text | html_stripped | pdf_extract | ocr  (NLP quality signal)',
  text_char_length          INT,
  source_table_or_resource  STRING,
  ingested_at               TIMESTAMP,
  loaded_at                 TIMESTAMP DEFAULT current_timestamp(),
  raw_payload               VARIANT,
  CONSTRAINT pk_clinical_note PRIMARY KEY (note_sk),
  CONSTRAINT fk_note_patient   FOREIGN KEY (patient_sk)         REFERENCES ehr_poc.silver.patient,
  CONSTRAINT fk_note_encounter FOREIGN KEY (encounter_sk)       REFERENCES ehr_poc.silver.encounter,
  CONSTRAINT fk_note_author    FOREIGN KEY (author_provider_sk) REFERENCES ehr_poc.silver.provider
)
COMMENT 'Unstructured clinical text. Epic: HNO_INFO+HNO_NOTE_TEXT (concat by LINE). athena: DocumentReference+Binary (PDF/HTML/OCR).'
CLUSTER BY (patient_sk, service_date);

-- -----------------------------------------------------------------------------
-- Domain 4 — Diagnoses
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS ehr_poc.silver.condition (
  condition_sk              BIGINT GENERATED BY DEFAULT AS IDENTITY,
  patient_sk                BIGINT NOT NULL,
  encounter_sk              BIGINT COMMENT 'NULL for standalone problem-list items',
  source_system             STRING NOT NULL,
  source_id                 STRING NOT NULL,
  category                  STRING COMMENT 'problem-list-item | encounter-diagnosis',
  condition_code            STRING COMMENT 'ICD-10-CM (and/or SNOMED)',
  condition_system          STRING,
  condition_display         STRING,
  condition_concept_sk      BIGINT COMMENT 'optional FK -> terminology.concept',
  clinical_status           STRING COMMENT 'active | resolved | inactive',
  verification_status       STRING COMMENT 'confirmed | provisional',
  rank                      INT COMMENT '1 = primary diagnosis',
  is_primary                BOOLEAN,
  is_chronic                BOOLEAN,
  onset_date                DATE,
  recorded_date             DATE,
  resolved_date             DATE,
  source_table_or_resource  STRING,
  ingested_at               TIMESTAMP,
  loaded_at                 TIMESTAMP DEFAULT current_timestamp(),
  raw_payload               VARIANT,
  CONSTRAINT pk_condition PRIMARY KEY (condition_sk),
  CONSTRAINT fk_cond_patient   FOREIGN KEY (patient_sk)   REFERENCES ehr_poc.silver.patient,
  CONSTRAINT fk_cond_encounter FOREIGN KEY (encounter_sk) REFERENCES ehr_poc.silver.encounter
)
COMMENT 'Diagnoses & problem list. Epic: PAT_ENC_DX/PROBLEM_LIST->EDG_CURRENT_ICD10. athena: Condition. Guard DX_ID<->ICD fan-out.'
CLUSTER BY (patient_sk, condition_code);

-- -----------------------------------------------------------------------------
-- Domain 5 — Medications
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS ehr_poc.silver.medication_order (
  med_order_sk              BIGINT GENERATED BY DEFAULT AS IDENTITY,
  patient_sk                BIGINT NOT NULL,
  encounter_sk              BIGINT,
  ordering_provider_sk      BIGINT,
  source_system             STRING NOT NULL,
  source_id                 STRING NOT NULL COMMENT 'Epic ORDER_MED_ID | FHIR MedicationRequest id',
  med_code                  STRING COMMENT 'RxNorm',
  med_system                STRING,
  med_display               STRING,
  ndc_code                  STRING,
  med_concept_sk            BIGINT COMMENT 'optional FK -> terminology.concept',
  order_class               STRING COMMENT 'inpatient | outpatient (prescription)',
  dose_quantity             DOUBLE,
  dose_unit                 STRING,
  route                     STRING,
  frequency                 STRING,
  sig_text                  STRING COMMENT 'free-text instructions (minor NLP target)',
  order_status              STRING COMMENT 'active | completed | discontinued',
  start_datetime            TIMESTAMP,
  end_datetime              TIMESTAMP,
  source_table_or_resource  STRING,
  ingested_at               TIMESTAMP,
  loaded_at                 TIMESTAMP DEFAULT current_timestamp(),
  raw_payload               VARIANT,
  CONSTRAINT pk_medication_order PRIMARY KEY (med_order_sk),
  CONSTRAINT fk_medord_patient   FOREIGN KEY (patient_sk)           REFERENCES ehr_poc.silver.patient,
  CONSTRAINT fk_medord_encounter FOREIGN KEY (encounter_sk)         REFERENCES ehr_poc.silver.encounter,
  CONSTRAINT fk_medord_provider  FOREIGN KEY (ordering_provider_sk) REFERENCES ehr_poc.silver.provider
)
COMMENT 'Medication orders/prescriptions. Epic: ORDER_MED->CLARITY_MEDICATION+RxNorm. athena: MedicationRequest/Statement.'
CLUSTER BY (patient_sk, start_datetime);

CREATE TABLE IF NOT EXISTS ehr_poc.silver.medication_administration (
  med_admin_sk              BIGINT GENERATED BY DEFAULT AS IDENTITY,
  med_order_sk              BIGINT,
  patient_sk                BIGINT NOT NULL,
  encounter_sk              BIGINT,
  source_system             STRING NOT NULL,
  source_id                 STRING NOT NULL COMMENT 'Epic MAR row | FHIR MedicationAdministration id',
  admin_datetime            TIMESTAMP,
  scheduled_datetime        TIMESTAMP,
  admin_action              STRING COMMENT 'given | held | refused',
  dose_given                DOUBLE,
  dose_unit                 STRING,
  route                     STRING,
  infusion_rate             DOUBLE,
  source_table_or_resource  STRING,
  ingested_at               TIMESTAMP,
  loaded_at                 TIMESTAMP DEFAULT current_timestamp(),
  raw_payload               VARIANT,
  CONSTRAINT pk_medication_administration PRIMARY KEY (med_admin_sk),
  CONSTRAINT fk_medadm_order     FOREIGN KEY (med_order_sk) REFERENCES ehr_poc.silver.medication_order,
  CONSTRAINT fk_medadm_patient   FOREIGN KEY (patient_sk)   REFERENCES ehr_poc.silver.patient,
  CONSTRAINT fk_medadm_encounter FOREIGN KEY (encounter_sk) REFERENCES ehr_poc.silver.encounter
)
COMMENT 'Medication Administration Record (actually given). Epic: MAR_ADMIN_INFO. athena: MedicationAdministration.'
CLUSTER BY (patient_sk, admin_datetime);

-- -----------------------------------------------------------------------------
-- Domain 6/8 support — Diagnostic Report (groups results; bridges to note text)
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS ehr_poc.silver.diagnostic_report (
  diagnostic_report_sk      BIGINT GENERATED BY DEFAULT AS IDENTITY,
  patient_sk                BIGINT NOT NULL,
  encounter_sk              BIGINT,
  source_system             STRING NOT NULL,
  source_id                 STRING NOT NULL,
  report_code               STRING COMMENT 'LOINC panel/report type',
  report_system             STRING,
  report_display            STRING,
  report_category           STRING COMMENT 'LAB | PATHOLOGY | RADIOLOGY | MICRO',
  status                    STRING,
  effective_datetime        TIMESTAMP,
  narrative_note_sk         BIGINT COMMENT 'FK -> clinical_note: path/rad free-text body',
  source_table_or_resource  STRING,
  ingested_at               TIMESTAMP,
  loaded_at                 TIMESTAMP DEFAULT current_timestamp(),
  raw_payload               VARIANT,
  CONSTRAINT pk_diagnostic_report PRIMARY KEY (diagnostic_report_sk),
  CONSTRAINT fk_dr_patient   FOREIGN KEY (patient_sk)        REFERENCES ehr_poc.silver.patient,
  CONSTRAINT fk_dr_encounter FOREIGN KEY (encounter_sk)      REFERENCES ehr_poc.silver.encounter,
  CONSTRAINT fk_dr_note      FOREIGN KEY (narrative_note_sk) REFERENCES ehr_poc.silver.clinical_note
)
COMMENT 'FHIR DiagnosticReport — groups lab/path/rad results; links narrative to clinical_note.'
CLUSTER BY (patient_sk, effective_datetime);

-- -----------------------------------------------------------------------------
-- Domains 6 & 8 — Lab Results + Vital Signs (unified Observation, by category)
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS ehr_poc.silver.observation (
  observation_sk            BIGINT GENERATED BY DEFAULT AS IDENTITY,
  patient_sk                BIGINT NOT NULL,
  encounter_sk              BIGINT,
  diagnostic_report_sk      BIGINT COMMENT 'groups lab results into a panel',
  parent_observation_sk     BIGINT COMMENT 'self-ref for components, e.g. BP -> systolic/diastolic (informational, not declared as FK)',
  source_system             STRING NOT NULL,
  source_id                 STRING NOT NULL,
  category                  STRING NOT NULL COMMENT 'laboratory | vital-signs',
  observation_code          STRING COMMENT 'LOINC',
  observation_system        STRING,
  observation_display       STRING,
  observation_concept_sk    BIGINT COMMENT 'optional FK -> terminology.concept',
  value_numeric             DOUBLE,
  value_string              STRING COMMENT 'non-numeric / coded results',
  unit                      STRING COMMENT 'UCUM',
  reference_range_low       DOUBLE,
  reference_range_high      DOUBLE,
  interpretation            STRING COMMENT 'normal | high | low | critical | abnormal',
  effective_datetime        TIMESTAMP,
  source_table_or_resource  STRING,
  ingested_at               TIMESTAMP,
  loaded_at                 TIMESTAMP DEFAULT current_timestamp(),
  raw_payload               VARIANT,
  CONSTRAINT pk_observation PRIMARY KEY (observation_sk),
  CONSTRAINT fk_obs_patient   FOREIGN KEY (patient_sk)           REFERENCES ehr_poc.silver.patient,
  CONSTRAINT fk_obs_encounter FOREIGN KEY (encounter_sk)         REFERENCES ehr_poc.silver.encounter,
  CONSTRAINT fk_obs_report    FOREIGN KEY (diagnostic_report_sk) REFERENCES ehr_poc.silver.diagnostic_report
)
COMMENT 'Labs (category=laboratory) + Vitals (category=vital-signs). Epic: ORDER_RESULTS / IP_FLWSHT_MEAS. athena: Observation. BP split into component rows.'
CLUSTER BY (patient_sk, observation_code, effective_datetime);

-- -----------------------------------------------------------------------------
-- Domain 7 — Procedures
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS ehr_poc.silver.procedure (
  procedure_sk              BIGINT GENERATED BY DEFAULT AS IDENTITY,
  patient_sk                BIGINT NOT NULL,
  encounter_sk              BIGINT,
  performer_provider_sk     BIGINT,
  source_system             STRING NOT NULL,
  source_id                 STRING NOT NULL,
  procedure_code            STRING COMMENT 'CPT / HCPCS (and/or SNOMED)',
  procedure_system          STRING,
  procedure_display         STRING,
  procedure_concept_sk      BIGINT COMMENT 'optional FK -> terminology.concept',
  procedure_category        STRING COMMENT 'surgical | diagnostic | therapeutic',
  status                    STRING COMMENT 'completed | in-progress',
  performed_datetime        TIMESTAMP,
  performed_period_end      TIMESTAMP,
  modifier_1                STRING,
  modifier_2                STRING,
  modifier_3                STRING,
  modifier_4                STRING,
  is_billed                 BOOLEAN COMMENT 'clinical vs billed distinction',
  source_table_or_resource  STRING,
  ingested_at               TIMESTAMP,
  loaded_at                 TIMESTAMP DEFAULT current_timestamp(),
  raw_payload               VARIANT,
  CONSTRAINT pk_procedure PRIMARY KEY (procedure_sk),
  CONSTRAINT fk_proc_patient   FOREIGN KEY (patient_sk)            REFERENCES ehr_poc.silver.patient,
  CONSTRAINT fk_proc_encounter FOREIGN KEY (encounter_sk)          REFERENCES ehr_poc.silver.encounter,
  CONSTRAINT fk_proc_provider  FOREIGN KEY (performer_provider_sk) REFERENCES ehr_poc.silver.provider
)
COMMENT 'Procedures. Epic: ORDER_PROC->CLARITY_EAP / ARPB_TRANSACTIONS. athena: Procedure (+ Charge/Claim).'
CLUSTER BY (patient_sk, performed_datetime);
