-- =============================================================================
-- 04_nlp.sql
-- NLP layer: pipeline run metadata + entities extracted from clinical_note.
--
-- This is what makes the model NLP-cohort-ready: extracted mentions are
-- structured and keyed to the SAME patient/encounter as the coded domains, so
-- NLP-derived findings participate in cohort logic exactly like ICD/RxNorm data.
-- =============================================================================

CREATE TABLE IF NOT EXISTS ehr_poc.nlp.nlp_run (
  nlp_run_sk        BIGINT GENERATED BY DEFAULT AS IDENTITY,
  model_name        STRING NOT NULL,
  model_version     STRING,
  pipeline_config   VARIANT COMMENT 'parameters, prompt/version, thresholds, etc.',
  run_started_at    TIMESTAMP,
  run_finished_at   TIMESTAMP,
  note_count        BIGINT,
  CONSTRAINT pk_nlp_run PRIMARY KEY (nlp_run_sk)
)
COMMENT 'One row per NLP pipeline execution — reproducibility & model versioning.';

CREATE TABLE IF NOT EXISTS ehr_poc.nlp.note_nlp_entity (
  entity_sk         BIGINT GENERATED BY DEFAULT AS IDENTITY,
  note_sk           BIGINT NOT NULL,
  patient_sk        BIGINT NOT NULL COMMENT 'denormalized for fast cohort joins',
  encounter_sk      BIGINT,
  nlp_run_sk        BIGINT NOT NULL,
  entity_type       STRING COMMENT 'problem | medication | lab | procedure | anatomy | finding',
  covered_text      STRING COMMENT 'the literal span as it appears in note_text',
  span_start        INT COMMENT 'char offset into clinical_note.note_text',
  span_end          INT,
  concept_code      STRING COMMENT 'normalized: SNOMED | RxNorm | ICD-10-CM | LOINC',
  concept_system    STRING,
  concept_display   STRING,
  concept_sk        BIGINT COMMENT 'optional FK -> terminology.concept',
  negation          BOOLEAN COMMENT 'true => negated mention (e.g. "no pneumonia")',
  certainty         STRING COMMENT 'positive | negated | uncertain | hypothetical',
  temporality       STRING COMMENT 'current | historical | family',
  subject           STRING COMMENT 'patient | family | other',
  confidence        DOUBLE COMMENT 'model score 0..1',
  loaded_at         TIMESTAMP DEFAULT current_timestamp(),
  CONSTRAINT pk_note_nlp_entity PRIMARY KEY (entity_sk),
  CONSTRAINT fk_nlp_note    FOREIGN KEY (note_sk)    REFERENCES ehr_poc.silver.clinical_note,
  CONSTRAINT fk_nlp_patient FOREIGN KEY (patient_sk) REFERENCES ehr_poc.silver.patient,
  CONSTRAINT fk_nlp_run     FOREIGN KEY (nlp_run_sk) REFERENCES ehr_poc.nlp.nlp_run
)
COMMENT 'NLP-extracted mentions with NegEx/ConText attributes (negation/certainty/temporality/subject) for trustworthy cohorts.'
CLUSTER BY (patient_sk, concept_code);
