-- =============================================================================
-- 04_nlp_tables.sql
-- NLP pipeline metadata and entity extraction output.
--
-- nlp_run     — one row per pipeline execution (reproducibility / versioning)
-- note_nlp_entity — one row per extracted mention, keyed to the same
--                   patient/encounter as the structured clinical tables so
--                   NLP-derived findings participate in cohort logic identically
--                   to ICD-coded diagnoses or RxNorm medication orders.
--
-- Key attributes for trustworthy cohorts (classic NegEx/ConText features):
--   negation   — "no evidence of pneumonia"  → negation=true
--   certainty  — positive | negated | uncertain | hypothetical
--   temporality — current | historical | family
--   subject    — patient | family | other
--
-- Run after 03_poc_clinical_tables.sql.
-- =============================================================================

CREATE TABLE IF NOT EXISTS dev.test_silver_ehr_clinical.nlp_run (
  nlp_run_sk       BIGINT GENERATED BY DEFAULT AS IDENTITY,
  model_name       STRING    NOT NULL  COMMENT 'e.g. medspacy, biobert, spark-nlp-clinical, claude-sonnet',
  model_version    STRING,
  run_started_at   TIMESTAMP,
  run_finished_at  TIMESTAMP,
  note_count       INT                 COMMENT 'number of notes processed in this run',
  loaded_at        TIMESTAMP DEFAULT current_timestamp(),
  CONSTRAINT pk_nlp_run PRIMARY KEY (nlp_run_sk) NOT ENFORCED RELY
)
COMMENT 'One row per NLP pipeline execution — enables reproducibility and model versioning.'
TBLPROPERTIES ('delta.feature.allowColumnDefaults' = 'supported');

CREATE TABLE IF NOT EXISTS dev.test_silver_ehr_clinical.note_nlp_entity (
  entity_sk       BIGINT GENERATED BY DEFAULT AS IDENTITY,
  note_sk         BIGINT    NOT NULL,
  patient_sk      BIGINT    NOT NULL  COMMENT 'denormalized from clinical_note for fast cohort joins',
  encounter_sk    BIGINT,
  nlp_run_sk      BIGINT    NOT NULL,
  entity_type     STRING              COMMENT 'problem | medication | lab | procedure | anatomy | finding',
  covered_text    STRING              COMMENT 'the literal text span as extracted from note_text',
  span_start      INT                 COMMENT 'character offset start in note_text',
  span_end        INT                 COMMENT 'character offset end in note_text',
  concept_code    STRING              COMMENT 'normalized concept code: SNOMED / RxNorm / ICD-10-CM / LOINC',
  concept_system  STRING,
  concept_display STRING,
  negation        BOOLEAN   DEFAULT false  COMMENT 'true if the mention is negated ("no diabetes", "denies chest pain")',
  certainty       STRING              COMMENT 'positive | negated | uncertain | hypothetical',
  temporality     STRING              COMMENT 'current | historical | family',
  subject         STRING    DEFAULT 'patient'  COMMENT 'patient | family | other',
  confidence      DOUBLE              COMMENT 'model confidence score 0–1',
  loaded_at       TIMESTAMP DEFAULT current_timestamp(),
  CONSTRAINT pk_note_nlp_entity PRIMARY KEY (entity_sk)    NOT ENFORCED RELY,
  CONSTRAINT fk_entity_note     FOREIGN KEY (note_sk)      REFERENCES dev.test_silver_ehr_clinical.clinical_note NOT ENFORCED RELY,
  CONSTRAINT fk_entity_patient  FOREIGN KEY (patient_sk)   REFERENCES dev.test_silver_ehr_clinical.patient       NOT ENFORCED RELY,
  CONSTRAINT fk_entity_run      FOREIGN KEY (nlp_run_sk)   REFERENCES dev.test_silver_ehr_clinical.nlp_run       NOT ENFORCED RELY
)
COMMENT 'NLP-extracted clinical entities from note_text. negation/certainty/temporality/subject prevent false-positive cohort matches.'
CLUSTER BY (patient_sk, entity_type)
TBLPROPERTIES ('delta.feature.allowColumnDefaults' = 'supported');
