-- =============================================================================
-- 05_cohort_tables.sql
-- Cohort definitions, membership, and optional wide patient feature table.
-- Schema: dev.test_gold_ehr_cohort
--
-- Cohort classification axes (2 dimensions):
--
--   cohort_type     — WHY the cohort was built:
--     condition     - patients sharing a medical condition (T2DM, heart failure)
--     exposure      - patients grouped by intervention/drug/procedure
--     control       - patients WITHOUT the condition/exposure (comparator arm)
--     operational   - built for care management: high-cost, risk stratification,
--                     quality reporting, care gap identification
--     administrative - trial recruitment, population health reporting, billing
--
--   cohort_category — WHEN relative to the data:
--     retrospective - built from historical EHR data; outcomes already recorded
--     prospective   - defined on current criteria; captures new data over time
--
-- Cross-schema FK: cohort_member and patient_feature reference
-- dev.test_silver_ehr_clinical.patient (informational only, NOT ENFORCED).
--
-- VARIANT requires DBR 15.3+; replace qualifying_evidence with STRING (JSON)
-- on older runtimes.
-- Run after 04_nlp_tables.sql.
-- =============================================================================

CREATE TABLE IF NOT EXISTS dev.test_gold_ehr_cohort.cohort_definition (
  cohort_sk               BIGINT GENERATED BY DEFAULT AS IDENTITY,
  name                    STRING    NOT NULL,
  description             STRING,

  -- -----------------------------------------------------------------------
  -- Classification
  -- -----------------------------------------------------------------------
  cohort_type             STRING              COMMENT 'condition | exposure | control | operational | administrative',
  cohort_category         STRING              COMMENT 'retrospective | prospective',

  -- -----------------------------------------------------------------------
  -- Primary anchor concept (the clinical entity that defines entry)
  -- -----------------------------------------------------------------------
  primary_concept_code    STRING              COMMENT 'Primary code defining cohort entry: ICD-10-CM, RxNorm, CPT, HCC, custom',
  primary_concept_system  STRING              COMMENT 'ICD-10-CM | RxNorm | CPT | LOINC | HCC | custom',
  primary_concept_display STRING              COMMENT 'Human-readable name of the anchor concept',

  -- -----------------------------------------------------------------------
  -- Cohort logic
  -- -----------------------------------------------------------------------
  definition_logic        STRING              COMMENT 'SQL or structured JSON describing all inclusion / exclusion criteria',
  is_nlp_derived          BOOLEAN   DEFAULT false  COMMENT 'true if any criterion references note_nlp_entity',

  -- -----------------------------------------------------------------------
  -- Temporal parameters
  -- -----------------------------------------------------------------------
  index_event_description STRING              COMMENT 'What triggers cohort entry — e.g. "first T2DM diagnosis", "first metformin Rx", "top-5% spend in rolling 12 months"',
  lookback_days           INT                 COMMENT 'Retrospective lookback window in days; NULL = full available history',
  follow_up_days          INT                 COMMENT 'Prospective follow-up window in days; NULL = open-ended (ongoing)',

  -- -----------------------------------------------------------------------
  -- Common inclusion / exclusion filters
  -- -----------------------------------------------------------------------
  min_age_years           INT                 COMMENT 'Minimum patient age at index date (null = no lower bound)',
  max_age_years           INT                 COMMENT 'Maximum patient age at index date (null = no upper bound)',

  -- -----------------------------------------------------------------------
  -- Control cohort linkage
  -- -----------------------------------------------------------------------
  comparison_cohort_sk    BIGINT              COMMENT 'FK → cohort_definition: links a control cohort to its case cohort for RR / efficacy calculations',

  -- -----------------------------------------------------------------------
  -- Lifecycle / versioning (reproducibility for regulatory audits)
  -- -----------------------------------------------------------------------
  status                  STRING    DEFAULT 'draft'  COMMENT 'draft | active | archived',
  version                 INT       DEFAULT 1        COMMENT 'Version number — increment when definition_logic changes; old versions archived',
  created_by              STRING,
  created_at              TIMESTAMP DEFAULT current_timestamp(),

  CONSTRAINT pk_cohort_definition PRIMARY KEY (cohort_sk) NOT ENFORCED RELY
)
COMMENT 'Named patient cohort definitions. cohort_type classifies by purpose (condition/exposure/control/operational/administrative). cohort_category distinguishes retrospective from prospective study design. Linked to members via cohort_member.'
TBLPROPERTIES ('delta.feature.allowColumnDefaults' = 'supported');

-- Index to support looking up cohorts by type / category in Genie queries
-- (informational; no physical enforcement)
-- ALTER TABLE dev.test_gold_ehr_cohort.cohort_definition
--   ADD CONSTRAINT uq_cohort_name_version UNIQUE (name, version) NOT ENFORCED RELY;

-- ---------------------------------------------------------------------------
-- cohort_member
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dev.test_gold_ehr_cohort.cohort_member (
  cohort_member_sk    BIGINT GENERATED BY DEFAULT AS IDENTITY,
  cohort_sk           BIGINT    NOT NULL,
  patient_sk          BIGINT    NOT NULL,

  -- index_date: when the patient FIRST met the cohort entry criteria.
  -- Distinct from qualified_at (load time) — used for time-zero anchoring
  -- in retrospective studies and as the enrollment date in prospective ones.
  index_date          DATE                COMMENT 'Date patient first met cohort entry criteria (time-zero anchor)',

  qualified_at        TIMESTAMP,
  qualifying_source   STRING              COMMENT 'coded | nlp | both — how the patient qualified',
  qualifying_evidence VARIANT             COMMENT 'the condition / observation / note_nlp_entity rows that triggered inclusion (VARIANT; requires DBR 15.3+)',
  loaded_at           TIMESTAMP DEFAULT current_timestamp(),

  CONSTRAINT pk_cohort_member  PRIMARY KEY (cohort_member_sk) NOT ENFORCED RELY,
  CONSTRAINT fk_cm_cohort      FOREIGN KEY (cohort_sk)   REFERENCES dev.test_gold_ehr_cohort.cohort_definition   NOT ENFORCED RELY,
  CONSTRAINT fk_cm_patient     FOREIGN KEY (patient_sk)  REFERENCES dev.test_silver_ehr_clinical.patient         NOT ENFORCED RELY
)
COMMENT 'Cohort membership with explainable provenance — WHY each patient qualified (coded vs NLP), index_date for time-zero anchoring, and qualifying_evidence for audit.'
CLUSTER BY (cohort_sk)
TBLPROPERTIES ('delta.feature.allowColumnDefaults' = 'supported');

-- ---------------------------------------------------------------------------
-- patient_feature  (optional — wide table for downstream ML / risk scoring)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dev.test_gold_ehr_cohort.patient_feature (
  patient_sk           BIGINT    NOT NULL,
  age_years            INT,
  sex                  STRING,
  race                 STRING,
  ethnicity            STRING,
  encounter_count      INT,
  inpatient_count      INT,
  ed_count             INT,
  active_problem_count INT,
  distinct_med_count   INT,
  last_a1c             DOUBLE    COMMENT 'most recent HbA1c value (LOINC 4548-4)',
  last_bp_systolic     DOUBLE    COMMENT 'most recent systolic BP (mmHg)',
  last_bp_diastolic    DOUBLE    COMMENT 'most recent diastolic BP (mmHg)',
  last_bmi             DOUBLE,
  nlp_finding_count    INT       COMMENT 'distinct positive (non-negated, current) NLP-derived findings',
  feature_asof_date    DATE,
  loaded_at            TIMESTAMP DEFAULT current_timestamp(),
  CONSTRAINT pk_patient_feature  PRIMARY KEY (patient_sk) NOT ENFORCED RELY,
  CONSTRAINT fk_pf_patient       FOREIGN KEY (patient_sk) REFERENCES dev.test_silver_ehr_clinical.patient NOT ENFORCED RELY
)
COMMENT 'Wide per-patient feature table assembled from silver + nlp tables. One row per patient. Extend columns as needed for ML risk models (HCC, SDOH, utilization).'
CLUSTER BY (patient_sk)
TBLPROPERTIES ('delta.feature.allowColumnDefaults' = 'supported');
