-- =============================================================================
-- 05_gold_cohort.sql
-- Mart layer: cohort definitions, membership (with coded/NLP provenance),
-- and an optional wide patient feature table for downstream ML.
-- =============================================================================

CREATE TABLE IF NOT EXISTS ehr_poc.gold.cohort_definition (
  cohort_sk         BIGINT GENERATED BY DEFAULT AS IDENTITY,
  name              STRING NOT NULL,
  description       STRING,
  definition_logic  STRING COMMENT 'SQL or JSON describing inclusion/exclusion',
  is_nlp_derived    BOOLEAN DEFAULT false COMMENT 'true if any criterion uses note_nlp_entity',
  created_by        STRING,
  created_at        TIMESTAMP DEFAULT current_timestamp(),
  CONSTRAINT pk_cohort_definition PRIMARY KEY (cohort_sk)
)
COMMENT 'Named patient cohorts and their definition logic.';

CREATE TABLE IF NOT EXISTS ehr_poc.gold.cohort_member (
  cohort_member_sk    BIGINT GENERATED BY DEFAULT AS IDENTITY,
  cohort_sk           BIGINT NOT NULL,
  patient_sk          BIGINT NOT NULL,
  qualified_at        TIMESTAMP,
  qualifying_source   STRING COMMENT 'coded | nlp | both — how the patient qualified',
  qualifying_evidence VARIANT COMMENT 'the condition/observation/note_nlp_entity rows that triggered inclusion',
  loaded_at           TIMESTAMP DEFAULT current_timestamp(),
  CONSTRAINT pk_cohort_member PRIMARY KEY (cohort_member_sk),
  CONSTRAINT fk_cm_cohort  FOREIGN KEY (cohort_sk)  REFERENCES ehr_poc.gold.cohort_definition,
  CONSTRAINT fk_cm_patient FOREIGN KEY (patient_sk) REFERENCES ehr_poc.silver.patient
)
COMMENT 'Cohort membership with dual (coded vs NLP) provenance — explains WHY each patient is included.'
CLUSTER BY (cohort_sk);

-- Optional: wide, one-row-per-patient feature table for ML / analytics.
CREATE TABLE IF NOT EXISTS ehr_poc.gold.patient_feature (
  patient_sk            BIGINT NOT NULL,
  age_years             INT,
  sex                   STRING,
  race                  STRING,
  ethnicity             STRING,
  encounter_count       INT,
  inpatient_count       INT,
  ed_count              INT,
  active_problem_count  INT,
  distinct_med_count    INT,
  last_a1c              DOUBLE,
  last_bp_systolic      DOUBLE,
  last_bp_diastolic     DOUBLE,
  last_bmi              DOUBLE,
  nlp_finding_count     INT COMMENT 'distinct positive note-derived findings',
  feature_asof_date     DATE,
  loaded_at             TIMESTAMP DEFAULT current_timestamp(),
  CONSTRAINT pk_patient_feature PRIMARY KEY (patient_sk),
  CONSTRAINT fk_pf_patient FOREIGN KEY (patient_sk) REFERENCES ehr_poc.silver.patient
)
COMMENT 'Wide per-patient feature mart assembled from silver + nlp (extend as needed).'
CLUSTER BY (patient_sk);
